name: Fees Validator (no-commit)

on:
  schedule:
    - cron: '17 7 * * *'   # daily at 07:17 UTC
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Only the script deps we actually need
      - name: Install deps for script
        run: npm i -D tsx typescript cheerio @supabase/supabase-js

      - name: Check required env present
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          [ -z "${SUPABASE_URL}" ] && echo "SUPABASE_URL missing" && exit 1 || true
          [ -z "${SUPABASE_SERVICE_ROLE_KEY}" ] && echo "SUPABASE_SERVICE_ROLE_KEY missing" && exit 1 || true
          echo "Env looks OK"

      - name: Run validator
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}   # optional
          ZENROWS_API_KEY: ${{ secrets.ZENROWS_API_KEY }}       # 👈 new
        run: npx tsx scripts/validate-fees-supabase.ts
